// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Estacionamento", b =>
                {
                    b.Property<int>("IdEstacionamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstacionamento"));

                    b.HasKey("IdEstacionamento");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("Domain.Entities.Vaga", b =>
                {
                    b.Property<int>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVaga"));

                    b.Property<int?>("EstacionamentoIdEstacionamento")
                        .HasColumnType("integer");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoVaga")
                        .HasColumnType("integer");

                    b.HasKey("IdVaga");

                    b.HasIndex("EstacionamentoIdEstacionamento");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVeiculo"));

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Placa")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("VagaId")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Domain.Entities.Vaga", b =>
                {
                    b.HasOne("Domain.Entities.Estacionamento", null)
                        .WithMany("Vagas")
                        .HasForeignKey("EstacionamentoIdEstacionamento");
                });

            modelBuilder.Entity("Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Domain.Entities.Vaga", null)
                        .WithOne("Veiculo")
                        .HasForeignKey("Domain.Entities.Veiculo", "VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Estacionamento", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("Domain.Entities.Vaga", b =>
                {
                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
